PROJECT_NAME: f_AnoGAN
EXP_NAME: f_anogan-yb

SEED: 0
MIXING_PRECISION: True
DEVICE: "cuda:0"
CUDNN_BENCHMARK: True

MODEL:
  G:
    NAME: "dcnet"

    LATENT_DIM: 100
    OUT_CHANNELS: 3
    CHANNELS: 64

    EMA: False
    COMPILED: False
  D:
    NAME: "discriminator"

    IN_CHANNELS: 3
    OUT_CHANNELS: 1
    CHANNELS: 64

    EMA: False
    COMPILED: False
  E:
    NAME: "encodernet"

    LATENT_DIM: 100
    IN_CHANNELS: 3
    CHANNELS: 64

    EMA: False
    COMPILED: False

  EMA:
    DECAY: 0.999
    COMPILED: False

  CHECKPOINT:
    PRETRAINED_G_MODEL_WEIGHTS_PATH: ""
    PRETRAINED_D_MODEL_WEIGHTS_PATH: ""
    PRETRAINED_E_MODEL_WEIGHTS_PATH: ""

    RESUME_G_MODEL_WEIGHTS_PATH: ""
    RESUME_D_MODEL_WEIGHTS_PATH: ""
    RESUME_E_MODEL_WEIGHTS_PATH: ""

TRAIN:
  DATASET:
    ROOT_DIR: "./data/S1000e-SiC-no_chip-normal_sub"

  HYP:
    EPOCHS: 200

    IMGS_PER_BATCH: 128
    SHUFFLE: True
    NUM_WORKERS: 4
    PIN_MEMORY: True
    DROP_LAST: True
    PERSISTENT_WORKERS: True

  LOSSES:
    GAN_CRITERION:
      NAME: "bce"
    E_CRITERION:
      NAME: "mse"

  OPTIMIZER:
    G:
      NAME: "adam"
      LR: 0.0002
      BETAS: [ 0.5, 0.999 ]
      WEIGHT_DECAY: 0.00001
    D:
      NAME: "adam"
      LR: 0.0002
      BETAS: [ 0.5, 0.999 ]
      WEIGHT_DECAY: 0.00001
    E:
      NAME: "adam"
      LR: 0.0002
      BETAS: [ 0.0, 0.999 ]

  N_CRITIC: 5

  PRINT_FREQ: 100







